#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
   {{0x63ecd7e3}, 1000},
   {{0x63ecd7e3}, 1001},
   {{0x63ecd7e3}, 1002},
   {{0x63ecd7e3}, 1003},
   {{0x63ecd7e3}, 1004},
   {{0x63ecd7e3}, 1005},
   {{0x63ecd7e3}, 1006},
   {{0x63ecd7e3}, 1007},
   {{0x63ecd7e3}, 1008},
   {{0x63ecd7e3}, 1009},
   {{0x63ecd7e3}, 1020},
   {{0x63ecd7e3}, 1021},
   {{0xc61b61ac}, 10000},
   {{0xc632f359}, 9999},
   {{0xc632f359}, 9998},
   {{0xc632f359}, 9997},
   {{0xc632f359}, 9996},
   {{0xc632f359}, 9995},
   {{0xc632f359}, 9994},
   {{0xc632f359}, 9993},
   {{0xc632f359}, 9992},
   {{0xc632f359}, 9991},
   {{0xc632f359}, 9990},
   {{0xc632f359}, 9989},
   {{0xc632f359}, 9987},
   {{0xc632f359}, 9986},
   {{0xc632f359}, 9985}
};


static const unsigned int SeedSpec6 pnTestnetSeed[] = {

};
#endif
